### ISSUE TITLE
Donation label is inconsistent with the amount donated when clicking a card

### ISSUE THREAD

**Issue by davidli3100** [jamrants/donations#52]
When clicking a card to match a donation, the donation slider label reads `that's more than X company!` even though the amount is equivalent.

**Comment by davidli3100** [comment]
Fixed in fdc0be78b87798ac3672cd91724c9a64c75d0bc7

**Comment by RetroCraft** [comment]
Still persists on edge cases (high orders of magnitude). We'll have to come up with a more permanent solution @davidli3100.
